### ISSUE TITLE
Toggling customize-panel-description also toggles resizer width

### ISSUE THREAD

**Issue by tywayne** [xwp/wp-customize-pane-resizer#10]
![resize-help-collapse](https://cloud.githubusercontent.com/assets/1395543/11732324/b34b8a50-9f68-11e5-92bb-424545814db7.gif)

**Comment by tywayne** [comment]
Similar ( but potentially different? ) issue when collapsing the expanded widgets/menu panel.

![resize-widget-collapse](https://cloud.githubusercontent.com/assets/1395543/11732520/9ec490b6-9f6a-11e5-8ac4-9167ba28af68.gif)

**Comment by NateWr** [comment]
This is caused by [this line](https://github.com/xwp/wp-customize-pane-resizer/blob/master/js/customizer-resizer.js#L84):

```
$( '[aria-expanded]' ).on( 'click', app.toggleExpansion );
```

Removing that line fixes the bug and doesn't seem to have any adverse effects in my testing. But I'm not sure what problem that line may have been meant to fix in the first place, so [my PR](https://github.com/xwp/wp-customize-pane-resizer/pull/13) might create more problems than it solves.
